//! The launch ABI, generated from the table.
//!
//! A launcher here is an authored C++ function in a nested namespace, with no
//! `extern "C"` anywhere and default arguments on several of them. None of
//! that is callable from outside C++, and the reason is not that it should be
//! — it is that the SIGNATURE was never written down. `KernelSig` carried
//! everything about a kernel except how to call it, and the argument list
//! lived only in the header and, informally, in the model bodies that call it.
//!
//! [`KernelSig::operands`] is that list. Given it, this module emits both
//! halves of a flat ABI:
//!
//! * [`emit_c_shim`] — one `extern "C"` function per row, which includes the
//!   real header and forwards to the real launcher;
//! * [`emit_rust_bindings`] — the matching `unsafe extern "C"` block.
//!
//! ## Why generating it is the proof
//!
//! The shim is not a translation layer that has to be trusted. It CALLS the
//! function it describes, with the header in scope, so C++ overload
//! resolution decides whether the row is right — arity, order, constness and
//! width, all at once, all as compile errors. A hand-written shim would need
//! a golden and a mutation suite to reach a weaker version of the same
//! claim; this needs neither, because a wrong row does not build.
//!
//! It also settles the crate's own invariant, that every symbol in the table
//! resolves to exactly one declaration and every declaration has exactly one
//! row. The first half becomes a tautology here. The second half is still a
//! count, and it is what the pilot found: `rope.hpp` declared twelve
//! launchers against ten rows.
//!
//! ## Scope
//!
//! Rows with an empty operand list are SKIPPED, not emitted as nullary. The
//! table is being filled a family at a time and an unstated row must not be
//! mistaken for a stated one — see [`KernelSig::operands`].

use kernels::KernelSig;

/// The prefix every generated entry point carries.
///
/// One underscore, not two: `__` anywhere in an identifier is reserved to the
/// implementation in C++, so the obvious `pie_k_rope__rope_bf16` spelling for
/// a `::`-joined path is not ours to use. [`entry_name`] therefore joins with
/// a single `_` and [`emit_c_shim`] rejects a collision rather than letting
/// two rows quietly share an entry point.
pub const PREFIX: &str = "pie_k_";

/// The `extern "C"` name for a row: the prefix, then the symbol with its
/// namespace separators flattened.
pub fn entry_name(symbol: &str) -> String {
    format!("{PREFIX}{}", symbol.replace("::", "_"))
}

/// The rows this module can emit — those that have stated their operands.
fn stated(table: &[&'static [KernelSig]]) -> Vec<&'static KernelSig> {
    table
        .iter()
        .flat_map(|t| t.iter())
        .filter(|k| !k.operands.is_empty())
        .collect()
}

/// The C++ namespace a symbol names, under this crate's root.
fn cpp_path(symbol: &str) -> String {
    format!("::pie_cuda_driver::kernels::{symbol}")
}

/// Emit the `extern "C"` forwarding shims for every stated row in `tables`.
///
/// `includes` are the headers the launchers are declared in, relative to
/// `csrc/src`. They are included by the generated TU, which is what makes
/// compiling it a proof of the rows.
///
/// Errors if two rows would produce the same entry point.
pub fn emit_c_shim(
    tables: &[&'static [KernelSig]],
    includes: &[&str],
) -> Result<String, String> {
    let rows = stated(tables);
    let mut seen: Vec<(String, &str)> = Vec::new();
    let mut out = String::new();

    out.push_str(
        "// GENERATED by kernels_cuda::abi::emit_c_shim -- do not edit.\n\
         //\n\
         // Each body forwards to the launcher its row describes, through a\n\
         // function pointer of the row's exact type. A function-pointer\n\
         // initialisation admits NO parameter conversions, which is why it is\n\
         // written this way rather than as a direct call: a direct call is\n\
         // checked by overload resolution, and overload resolution accepts\n\
         // `void*` where the callee takes `const void*`. That is the one\n\
         // direction a shim can be wrong in and still compile -- a row\n\
         // claiming a read-only operand is written -- and it is exactly the\n\
         // fact the table exists to carry.\n\n\
         #include <cstddef>\n\
         #include <cstdint>\n\
         #include <cuda_runtime.h>\n\n",
    );
    for inc in includes {
        out.push_str(&format!("#include \"{inc}\"\n"));
    }
    out.push('\n');

    for k in rows {
        let entry = entry_name(k.symbol);
        if let Some((_, other)) = seen.iter().find(|(e, _)| *e == entry) {
            return Err(format!(
                "entry point `{entry}` is claimed by both `{}` and `{other}`",
                k.symbol
            ));
        }
        seen.push((entry.clone(), k.symbol));

        let params = k
            .operands
            .iter()
            .map(|o| format!("    {} {}", o.ty.cpp(), o.name))
            .collect::<Vec<_>>()
            .join(",\n");
        let types = k
            .operands
            .iter()
            .map(|o| o.ty.cpp())
            .collect::<Vec<_>>()
            .join(", ");
        let args = k
            .operands
            .iter()
            .map(|o| o.name)
            .collect::<Vec<_>>()
            .join(", ");

        out.push_str(&format!(
            "extern \"C\" void {entry}(\n{params}) {{\n    \
             static void (*const fwd)({types}) = &{};\n    \
             fwd({args});\n}}\n\n",
            cpp_path(k.symbol),
        ));
    }
    Ok(out)
}

/// Emit the Rust `extern "C"` block matching [`emit_c_shim`].
///
/// Both sides read the same rows, so they cannot disagree with each other;
/// what the shim adds is that they cannot disagree with the C++ either.
pub fn emit_rust_bindings(tables: &[&'static [KernelSig]]) -> String {
    let mut out = String::from(
        "// GENERATED by kernels_cuda::abi::emit_rust_bindings -- do not edit.\n\
         //\n\
         // The other half of the same rows the C++ shim is generated from.\n\
         // A `nullable` operand is documented, not typed: making it an\n\
         // `Option<NonNull<_>>` here would change the calling convention of\n\
         // an `extern \"C\"` declaration for a fact the callee checks itself.\n\n\
         unsafe extern \"C\" {\n",
    );
    for k in stated(tables) {
        out.push_str(&format!("    /// `{}`\n", k.symbol));
        out.push_str(&format!("    pub unsafe fn {}(\n", entry_name(k.symbol)));
        for o in k.operands {
            let note = if o.nullable { "  // may be null" } else { "" };
            out.push_str(&format!("        {}: {},{note}\n", o.name, o.ty.rust()));
        }
        out.push_str("    );\n");
    }
    out.push_str("}\n");
    out
}

/// One record whose Rust mirror claims to have the C++ type's layout.
///
/// The offsets are the RUST side's, read off the mirror with `offset_of!`.
/// Nothing here is trusted: they are baked into a generated C++ file as
/// `static_assert`s and checked where both layouts are known. Neither side
/// states a number a human wrote down, so there is nothing to keep in sync.
pub struct Record {
    /// The fully-qualified C++ type.
    pub cpp: &'static str,
    /// `size_of` the Rust mirror.
    pub size: usize,
    /// `align_of` the Rust mirror.
    pub align: usize,
    /// Every field, in declaration order, with the Rust mirror's offset.
    pub fields: Vec<(&'static str, usize)>,
}

/// Build a [`Record`] from a `#[repr(C)]` mirror and the C++ type it claims.
///
/// The field list is written once, and both the offsets and the member-count
/// check are derived from it.
#[macro_export]
macro_rules! record {
    ($rust:ty => $cpp:literal { $($field:ident),* $(,)? }) => {
        $crate::abi::Record {
            cpp: $cpp,
            size: ::core::mem::size_of::<$rust>(),
            align: ::core::mem::align_of::<$rust>(),
            fields: ::std::vec![
                $((stringify!($field), ::core::mem::offset_of!($rust, $field))),*
            ],
        }
    };
}

/// Emit a translation unit that asserts each mirror's layout against the C++.
///
/// Three claims per record, and it takes all three to be exhaustive:
///
/// * `sizeof` and `alignof` — the shape of the whole;
/// * every field's `offsetof` — that each member is where the mirror puts it;
/// * a structured binding over the whole record — that there are no OTHER
///   members. This one is not decoration. A field added to the end of the C++
///   would land in the tail padding an aligned record already has, leave
///   `sizeof` unchanged, and disturb no existing offset, so the first two
///   claims would both still hold while the mirror silently stopped
///   describing the type. A structured binding names members positionally and
///   the count must match exactly, which is the only standard C++20 way to
///   say "and that is all of them".
pub fn emit_layout_assertions(records: &[Record], includes: &[&str]) -> String {
    let mut out = String::from(
        "// GENERATED by kernels_cuda::abi::emit_layout_assertions -- do not edit.\n\
         //\n\
         // The offsets are what the RUST mirrors compute for themselves. They\n\
         // are checked here because this is the only place both layouts are\n\
         // known; a mirror that disagrees does not compile.\n\n\
         #include <cstddef>\n\
         #include <cstdint>\n\n",
    );
    for inc in includes {
        out.push_str(&format!("#include \"{inc}\"\n"));
    }
    out.push('\n');

    for r in records {
        let tag = r.cpp.rsplit("::").next().unwrap_or(r.cpp);
        out.push_str(&format!(
            "static_assert(sizeof({0}) == {1},\n    \
             \"{0}: the mirror is {1} bytes\");\n\
             static_assert(alignof({0}) == {2},\n    \
             \"{0}: the mirror aligns to {2}\");\n",
            r.cpp, r.size, r.align
        ));
        for (name, off) in &r.fields {
            out.push_str(&format!(
                "static_assert(offsetof({0}, {1}) == {2},\n    \
                 \"{0}::{1} is not at {2}\");\n",
                r.cpp, name, off
            ));
        }
        let binds = r
            .fields
            .iter()
            .map(|(n, _)| format!("f_{n}"))
            .collect::<Vec<_>>();
        out.push_str(&format!(
            "\n// Exactly {} members, and no more.\nnamespace {{\ninline void \
             abi_member_count_{tag}() {{\n    {} v{{}};\n    auto& [{}] = v;\n{}}}\n}}\n\n",
            binds.len(),
            r.cpp,
            binds.join(", "),
            binds
                .iter()
                .map(|b| format!("    (void){b};\n"))
                .collect::<String>(),
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use kernels::Ty;

    /// The two emitters must describe the same operands in the same order, or
    /// the C++ side proves a signature the Rust side does not call.
    #[test]
    fn both_halves_are_emitted_from_the_same_rows() {
        let tables: &[&'static [KernelSig]] = &[crate::rope::KERNELS];
        let c = emit_c_shim(tables, &["rope/rope.hpp"]).expect("no collisions");
        let rs = emit_rust_bindings(tables);
        for k in stated(tables) {
            let entry = entry_name(k.symbol);
            assert!(c.contains(&entry), "{entry} missing from the shim");
            assert!(rs.contains(&entry), "{entry} missing from the bindings");
            for o in k.operands {
                assert!(c.contains(o.name), "{entry}: {} missing", o.name);
            }
        }
    }

    /// An unstated row is skipped rather than emitted as a nullary call.
    #[test]
    fn rows_that_have_not_stated_their_operands_are_not_emitted() {
        static UNSTATED: &[KernelSig] = &[kernels::kernel!(nothing "fam::not_yet_stated")];
        let c = emit_c_shim(&[UNSTATED], &[]).expect("no collisions");
        assert!(!c.contains("not_yet_stated"));
        assert!(!emit_rust_bindings(&[UNSTATED]).contains("not_yet_stated"));
    }

    /// `::` flattens to a single underscore -- `__` is reserved in C++.
    #[test]
    fn entry_points_avoid_the_reserved_double_underscore() {
        let name = entry_name("rope::rope_bf16");
        assert_eq!(name, "pie_k_rope_rope_bf16");
        assert!(!name.contains("__"));
    }

    /// Which makes a collision possible in principle, so it is refused.
    #[test]
    fn two_rows_may_not_claim_one_entry_point() {
        static CLASH: &[KernelSig] = &[
            kernels::kernel!(a "rope::a_b", operands = kernels::operands![stream: Stream]),
            kernels::kernel!(b "rope_a::b", operands = kernels::operands![stream: Stream]),
        ];
        let err = emit_c_shim(&[CLASH], &[]).expect_err("a collision is an error");
        assert!(err.contains("pie_k_rope_a_b"), "{err}");
    }

    /// `bool` is one byte in C++ and `int` is four. A binding that renders a
    /// flag as an `int` mis-lays every operand after it, and no compiler on
    /// either side would say so -- which is why `Bool` is its own kind.
    #[test]
    fn a_flag_stays_one_byte_wide_on_both_sides() {
        assert_eq!(Ty::Bool.cpp(), "bool");
        assert_eq!(Ty::Bool.rust(), "bool");
        assert_ne!(Ty::Bool.rust(), Ty::I32.rust());
    }
}
