//! The launch ABI, generated from the table.
//!
//! A launcher here is an authored C++ function in a nested namespace, with no
//! `extern "C"` anywhere and default arguments on several of them. None of
//! that is callable from outside C++, and the reason is not that it should be
//! — it is that the SIGNATURE was never written down. `KernelSig` carried
//! everything about a kernel except how to call it, and the argument list
//! lived only in the header and, informally, in the model bodies that call it.
//!
//! [`KernelSig::operands`] is that list. Given it, this module emits both
//! halves of a flat ABI:
//!
//! * [`emit_c_shim`] — one `extern "C"` function per row, which includes the
//!   real header and forwards to the real launcher;
//! * [`emit_rust_bindings`] — the matching `unsafe extern "C"` block.
//!
//! ## Why generating it is the proof
//!
//! The shim is not a translation layer that has to be trusted. It CALLS the
//! function it describes, with the header in scope, so C++ overload
//! resolution decides whether the row is right — arity, order, constness and
//! width, all at once, all as compile errors. A hand-written shim would need
//! a golden and a mutation suite to reach a weaker version of the same
//! claim; this needs neither, because a wrong row does not build.
//!
//! It also settles the crate's own invariant, that every symbol in the table
//! resolves to exactly one declaration and every declaration has exactly one
//! row. The first half becomes a tautology here. The second half is still a
//! count, and it is what the pilot found: `rope.hpp` declared twelve
//! launchers against ten rows.
//!
//! ## Scope
//!
//! Rows with an empty operand list are SKIPPED, not emitted as nullary. The
//! table is being filled a family at a time and an unstated row must not be
//! mistaken for a stated one — see [`KernelSig::operands`].

use kernels::KernelSig;

/// The prefix every generated entry point carries.
///
/// One underscore, not two: `__` anywhere in an identifier is reserved to the
/// implementation in C++, so the obvious `pie_k_rope__rope_bf16` spelling for
/// a `::`-joined path is not ours to use. [`entry_name`] therefore joins with
/// a single `_` and [`emit_c_shim`] rejects a collision rather than letting
/// two rows quietly share an entry point.
pub const PREFIX: &str = "pie_k_";

/// The `extern "C"` name for a row: the prefix, then the symbol with its
/// namespace separators flattened.
pub fn entry_name(symbol: &str) -> String {
    format!("{PREFIX}{}", symbol.replace("::", "_"))
}

/// The rows this module can emit — those that have stated their operands.
fn stated(table: &[&'static [KernelSig]]) -> Vec<&'static KernelSig> {
    table
        .iter()
        .flat_map(|t| t.iter())
        .filter(|k| !k.operands.is_empty())
        .collect()
}

/// The C++ namespace a symbol names, under this crate's root.
fn cpp_path(symbol: &str) -> String {
    format!("::pie_cuda_driver::kernels::{symbol}")
}

/// Emit the `extern "C"` forwarding shims for every stated row in `tables`.
///
/// `includes` are the headers the launchers are declared in, relative to
/// `csrc/src`. They are included by the generated TU, which is what makes
/// compiling it a proof of the rows.
///
/// Errors if two rows would produce the same entry point.
pub fn emit_c_shim(
    tables: &[&'static [KernelSig]],
    includes: &[&str],
) -> Result<String, String> {
    let rows = stated(tables);
    let mut seen: Vec<(String, &str)> = Vec::new();
    let mut out = String::new();

    out.push_str(
        "// GENERATED by kernels_cuda::abi::emit_c_shim -- do not edit.\n\
         //\n\
         // Each body forwards to the launcher its row describes, through a\n\
         // function pointer of the row's exact type. A function-pointer\n\
         // initialisation admits NO parameter conversions, which is why it is\n\
         // written this way rather than as a direct call: a direct call is\n\
         // checked by overload resolution, and overload resolution accepts\n\
         // `void*` where the callee takes `const void*`. That is the one\n\
         // direction a shim can be wrong in and still compile -- a row\n\
         // claiming a read-only operand is written -- and it is exactly the\n\
         // fact the table exists to carry.\n\n\
         #include <cstddef>\n\
         #include <cstdint>\n\
         #include <cuda_runtime.h>\n\n",
    );
    for inc in includes {
        out.push_str(&format!("#include \"{inc}\"\n"));
    }
    out.push('\n');

    for k in rows {
        let entry = entry_name(k.symbol);
        if let Some((_, other)) = seen.iter().find(|(e, _)| *e == entry) {
            return Err(format!(
                "entry point `{entry}` is claimed by both `{}` and `{other}`",
                k.symbol
            ));
        }
        seen.push((entry.clone(), k.symbol));

        let params = k
            .operands
            .iter()
            .map(|o| format!("    {} {}", o.ty.cpp(), o.name))
            .collect::<Vec<_>>()
            .join(",\n");
        let types = k
            .operands
            .iter()
            .map(|o| o.ty.cpp())
            .collect::<Vec<_>>()
            .join(", ");
        let args = k
            .operands
            .iter()
            .map(|o| o.name)
            .collect::<Vec<_>>()
            .join(", ");

        // A launcher that ANSWERS something keeps its answer: the shim
        // declares the forwarding pointer with the callee's real return
        // type, so a row that said `void` about a `bool` launcher is a
        // conversion C++ refuses rather than a value quietly dropped.
        let ret = if k.returns.is_empty() { "void" } else { k.returns };
        let forward = if k.returns.is_empty() {
            format!("    fwd({args});")
        } else {
            format!("    return fwd({args});")
        };
        out.push_str(&format!(
            "extern \"C\" {ret} {entry}(\n{params}) {{\n    \
             static {ret} (*const fwd)({types}) = &{};\n\
             {forward}\n}}\n\n",
            cpp_path(k.symbol),
        ));
    }
    Ok(out)
}

/// Emit the Rust `extern "C"` block matching [`emit_c_shim`].
///
/// Both sides read the same rows, so they cannot disagree with each other;
/// what the shim adds is that they cannot disagree with the C++ either.
pub fn emit_rust_bindings(tables: &[&'static [KernelSig]]) -> String {
    let mut out = String::from(
        "// GENERATED by kernels_cuda::abi::emit_rust_bindings -- do not edit.\n\
         //\n\
         // The other half of the same rows the C++ shim is generated from.\n\
         // A `nullable` operand is documented, not typed: making it an\n\
         // `Option<NonNull<_>>` here would change the calling convention of\n\
         // an `extern \"C\"` declaration for a fact the callee checks itself.\n\n\
         unsafe extern \"C\" {\n",
    );
    for k in stated(tables) {
        out.push_str(&format!("    /// `{}`\n", k.symbol));
        out.push_str(&format!("    pub unsafe fn {}(\n", entry_name(k.symbol)));
        for o in k.operands {
            let note = if o.nullable { "  // may be null" } else { "" };
            out.push_str(&format!("        {}: {},{note}\n", o.name, o.ty.rust()));
        }
        // The Rust side keeps the answer too. `bool` is the only
        // non-void return in the table and it is one byte on both
        // sides, which the layout suite already pins for `Ty::Bool`.
        if k.returns.is_empty() {
            out.push_str("    );\n");
        } else {
            let rust_ret = match k.returns {
                "bool" => "bool",
                other => panic!(
                    "abi: no Rust spelling for the return type `{other}`"
                ),
            };
            out.push_str(&format!("    ) -> {rust_ret};\n"));
        }
    }
    out.push_str("}\n");
    out
}

/// One record whose Rust mirror claims to have the C++ type's layout.
///
/// The offsets are the RUST side's, read off the mirror with `offset_of!`.
/// Nothing here is trusted: they are baked into a generated C++ file as
/// `static_assert`s and checked where both layouts are known. Neither side
/// states a number a human wrote down, so there is nothing to keep in sync.
pub struct Record {
    /// The fully-qualified C++ type.
    pub cpp: &'static str,
    /// `size_of` the Rust mirror.
    pub size: usize,
    /// `align_of` the Rust mirror.
    pub align: usize,
    /// Every field, in declaration order, with the Rust mirror's offset.
    pub fields: Vec<(&'static str, usize)>,
}

/// Build a [`Record`] from a `#[repr(C)]` mirror and the C++ type it claims.
///
/// The field list is written once, and both the offsets and the member-count
/// check are derived from it.
#[macro_export]
macro_rules! record {
    ($rust:ty => $cpp:literal { $($field:ident),* $(,)? }) => {
        $crate::abi::Record {
            cpp: $cpp,
            size: ::core::mem::size_of::<$rust>(),
            align: ::core::mem::align_of::<$rust>(),
            fields: ::std::vec![
                $((stringify!($field), ::core::mem::offset_of!($rust, $field))),*
            ],
        }
    };
}

/// Emit a translation unit that asserts each mirror's layout against the C++.
///
/// Three claims per record, and it takes all three to be exhaustive:
///
/// * `sizeof` and `alignof` — the shape of the whole;
/// * every field's `offsetof` — that each member is where the mirror puts it;
/// * a structured binding over the whole record — that there are no OTHER
///   members. This one is not decoration. A field added to the end of the C++
///   would land in the tail padding an aligned record already has, leave
///   `sizeof` unchanged, and disturb no existing offset, so the first two
///   claims would both still hold while the mirror silently stopped
///   describing the type. A structured binding names members positionally and
///   the count must match exactly, which is the only standard C++20 way to
///   say "and that is all of them".
pub fn emit_layout_assertions(records: &[Record], includes: &[&str]) -> String {
    let mut out = String::from(
        "// GENERATED by kernels_cuda::abi::emit_layout_assertions -- do not edit.\n\
         //\n\
         // The offsets are what the RUST mirrors compute for themselves. They\n\
         // are checked here because this is the only place both layouts are\n\
         // known; a mirror that disagrees does not compile.\n\n\
         #include <cstddef>\n\
         #include <cstdint>\n\n",
    );
    for inc in includes {
        out.push_str(&format!("#include \"{inc}\"\n"));
    }
    out.push('\n');

    for r in records {
        let tag = r.cpp.rsplit("::").next().unwrap_or(r.cpp);
        out.push_str(&format!(
            "static_assert(sizeof({0}) == {1},\n    \
             \"{0}: the mirror is {1} bytes\");\n\
             static_assert(alignof({0}) == {2},\n    \
             \"{0}: the mirror aligns to {2}\");\n",
            r.cpp, r.size, r.align
        ));
        for (name, off) in &r.fields {
            out.push_str(&format!(
                "static_assert(offsetof({0}, {1}) == {2},\n    \
                 \"{0}::{1} is not at {2}\");\n",
                r.cpp, name, off
            ));
        }
        let binds = r
            .fields
            .iter()
            .map(|(n, _)| format!("f_{n}"))
            .collect::<Vec<_>>();
        out.push_str(&format!(
            "\n// Exactly {} members, and no more.\nnamespace {{\ninline void \
             abi_member_count_{tag}() {{\n    {} v{{}};\n    auto& [{}] = v;\n{}}}\n}}\n\n",
            binds.len(),
            r.cpp,
            binds.join(", "),
            binds
                .iter()
                .map(|b| format!("    (void){b};\n"))
                .collect::<String>(),
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use kernels::Ty;

    /// The two emitters must describe the same operands in the same order, or
    /// the C++ side proves a signature the Rust side does not call.
    #[test]
    fn both_halves_are_emitted_from_the_same_rows() {
        let tables: &[&'static [KernelSig]] = &[crate::rope::KERNELS];
        let c = emit_c_shim(tables, &["rope/rope.hpp"]).expect("no collisions");
        let rs = emit_rust_bindings(tables);
        for k in stated(tables) {
            let entry = entry_name(k.symbol);
            assert!(c.contains(&entry), "{entry} missing from the shim");
            assert!(rs.contains(&entry), "{entry} missing from the bindings");
            for o in k.operands {
                assert!(c.contains(o.name), "{entry}: {} missing", o.name);
            }
        }
    }

    /// An unstated row is skipped rather than emitted as a nullary call.
    #[test]
    fn rows_that_have_not_stated_their_operands_are_not_emitted() {
        static UNSTATED: &[KernelSig] = &[kernels::kernel!(nothing "fam::not_yet_stated")];
        let c = emit_c_shim(&[UNSTATED], &[]).expect("no collisions");
        assert!(!c.contains("not_yet_stated"));
        assert!(!emit_rust_bindings(&[UNSTATED]).contains("not_yet_stated"));
    }

    /// `::` flattens to a single underscore -- `__` is reserved in C++.
    #[test]
    fn entry_points_avoid_the_reserved_double_underscore() {
        let name = entry_name("rope::rope_bf16");
        assert_eq!(name, "pie_k_rope_rope_bf16");
        assert!(!name.contains("__"));
    }

    /// Which makes a collision possible in principle, so it is refused.
    #[test]
    fn two_rows_may_not_claim_one_entry_point() {
        static CLASH: &[KernelSig] = &[
            kernels::kernel!(a "rope::a_b", operands = kernels::operands![stream: Stream]),
            kernels::kernel!(b "rope_a::b", operands = kernels::operands![stream: Stream]),
        ];
        let err = emit_c_shim(&[CLASH], &[]).expect_err("a collision is an error");
        assert!(err.contains("pie_k_rope_a_b"), "{err}");
    }

    /// `bool` is one byte in C++ and `int` is four. A binding that renders a
    /// flag as an `int` mis-lays every operand after it, and no compiler on
    /// either side would say so -- which is why `Bool` is its own kind.
    #[test]
    fn a_flag_stays_one_byte_wide_on_both_sides() {
        assert_eq!(Ty::Bool.cpp(), "bool");
        assert_eq!(Ty::Bool.rust(), "bool");
        assert_ne!(Ty::Bool.rust(), Ty::I32.rust());
    }
}

// ── THE GENERATED DISPATCH ─────────────────────────────────────────
//
// [`emit_c_shim`] proved a row describes its launcher. This is what the
// proof was FOR: given the types and the sources, the call itself is
// derivable, and the arm nobody has to write is the arm nobody can
// write wrong.
//
// What comes out is still a `switch`. C++ has no way to call a function
// with a dynamically built argument list without libffi or a trampoline
// per signature, and neither is worth the trade — so the switch stays
// and stops being HAND-written, which is the part that mattered. Adding
// a kernel becomes a row plus its sources; the dispatch regenerates.
//
// A row with any [`Source::Unbound`] operand is SKIPPED, on the same
// rule an unstated row is: a partial binding is not a binding, and a
// generator that filled the gaps with guesses would be the hand-written
// arm again with worse provenance.

use kernels::Source;

/// The C++ expression that binds one operand, given the context
/// variable's name.
fn bind_expr(op: &kernels::Operand, ctx: &str) -> Option<String> {
    let e = match op.source {
        Source::Unbound => return None,
        Source::In(i) => format!("{ctx}.arm.values.slot(ins[{i}])"),
        Source::Out(i) => format!("{ctx}.arm.values.slot(outs[{i}])"),
        Source::Weight(i) => {
            format!("{ctx}.wb.require({ctx}.arm.plan.name(aux[{i}])).data()")
        }
        Source::Param(i) => format!("static_cast<int>(ps[{i}])"),
        Source::Rows => format!("{ctx}.arm.rows"),
        Source::OutWidth(i) => format!("row_width({ctx}.arm.plan, outs[{i}])"),
        Source::InWidth(i) => format!("row_width({ctx}.arm.plan, ins[{i}])"),
        Source::OutElements(i) => format!(
            "static_cast<::std::size_t>({ctx}.arm.rows) * \
             static_cast<::std::size_t>(row_width({ctx}.arm.plan, outs[{i}]))"
        ),
        Source::InDim(i, d) => format!(
            "static_cast<int>({ctx}.arm.plan.value(ins[{i}]).dims[{d}].value)"
        ),
        Source::OutDim(i, d) => format!(
            "static_cast<int>({ctx}.arm.plan.value(outs[{i}]).dims[{d}].value)"
        ),
        Source::Ctx(f) | Source::CtxNonZero(f) => format!("{ctx}.{f}"),
        Source::Lit(l) => l.to_string(),
    };
    // The generated call goes through the flat ABI entry point, whose
    // parameter types are the row's — so a cast that the row does not
    // justify cannot be written here.
    Some(match op.ty {
        kernels::Ty::Buf | kernels::Ty::BufMut => e,
        kernels::Ty::I32sMut => format!("static_cast<::std::int32_t*>({e})"),
        kernels::Ty::F32sMut => format!("static_cast<float*>({e})"),
        kernels::Ty::F32s => format!("static_cast<const float*>({e})"),
        _ => e,
    })
}

/// Emit one `case` per row whose operands are fully sourced.
///
/// `ctx` is the C++ name of the `declared::ExecCtx` in scope. The body
/// assumes `ins`, `outs`, `aux` and `ps` are already bound — the caller
/// emits those once, because every case wants them and re-reading the
/// plan per case would be the generator's own duplication.
pub fn emit_dispatch(tables: &[&'static [KernelSig]], ctx: &str) -> String {
    let mut out = String::from(
        "// GENERATED by `kernels_cuda::abi::emit_dispatch` — DO NOT EDIT.\n\
         //\n\
         // One branch per kernel! row that states both its operand types\n\
         // and where each argument comes from. A row missing either is\n\
         // absent here and belongs to a hand-written arm until it states\n\
         // them.\n\
         //\n\
         // Keyed by the SYMBOL. The registry's enum is a handle a\n\
         // hand-written switch needed; this needs none, and the symbol\n\
         // is what the statement carries anyway.\n\n",
    );
    for k in stated(tables) {
        let binds: Option<Vec<String>> =
            k.operands.iter().map(|o| bind_expr(o, ctx)).collect();
        let Some(binds) = binds else { continue };
        // THE ARITY THE SOURCES ASK FOR, as part of the match.
        //
        // A branch that indexes `outs[1]` must not run on a statement
        // with one result, and rope is exactly that case: its Q-ONLY
        // spelling states one, reaches the same launcher with
        // `num_kv_heads = 0`, and would have read past the span here --
        // which does not fault, it reads the NEXT statement's operands
        // (the reason `need` exists at all).
        //
        // So the generated branch tests what it is about to index, and
        // a statement that does not satisfy it falls through to the
        // hand-written arm that knows the other spelling.
        let mut need_in = 0u8;
        let mut need_out = 0u8;
        let mut need_aux = 0u8;
        let mut need_ps = 0u8;
        for o in k.operands {
            match o.source {
                Source::In(i) | Source::InWidth(i) | Source::InDim(i, _) => {
                    need_in = need_in.max(i + 1)
                }
                Source::Out(i)
                | Source::OutWidth(i)
                | Source::OutDim(i, _)
                | Source::OutElements(i) => need_out = need_out.max(i + 1),
                Source::Weight(i) => need_aux = need_aux.max(i + 1),
                Source::Param(i) => need_ps = need_ps.max(i + 1),
                _ => {}
            }
        }
        let mut guard = String::new();
        for (n, span) in [
            (need_in, "ins"),
            (need_out, "outs"),
            (need_aux, "aux"),
            (need_ps, "ps"),
        ] {
            if n > 0 {
                guard.push_str(&format!(" && {span}.size >= {n}"));
            }
        }
        // WHAT `Source::Rows` ASSUMES, made part of the match.
        //
        // `Rows` binds the RECTANGLE's row count, which is the fire's
        // token count. That is the right answer only for a statement
        // whose rows ARE tokens, and not every statement's are: the
        // aligned MoE leg's values are `Dim::MoeAlignedRoutes`, a padded
        // block-major extent, and a branch handing that kernel `N`
        // activates the first N of the padded rows and leaves the rest
        // holding whatever the GEMM wrote.
        //
        // qwen3.5's routed swiglu is exactly that statement, and it
        // reached this generated branch before its family's arm — which
        // computes the padded count — could see it. So the branch tests
        // the assumption it is making, and a statement that does not
        // meet it falls through to the arm that knows the other extent.
        // A field a family zeroes to say "not mine" — see
        // `Source::CtxNonZero`. The guard is the row's, not the reading
        // arm's, which is what makes it survive the arm being generated.
        for o in k.operands {
            if let Source::CtxNonZero(f) = o.source {
                guard.push_str(&format!(" && {ctx}.{f} != 0"));
            }
        }
        if k.operands.iter().any(|o| o.source == Source::Rows) {
            let probe = if need_out > 0 { "outs[0]" } else { "ins[0]" };
            if need_out > 0 || need_in > 0 {
                guard.push_str(&format!(
                    " && c.arm.plan.value({probe}).dims[0].kind == \
                     pie_forward::PieForwardDimKind::Tokens"
                ));
            }
        }
        // KEYED BY NAME, not by an enumerator. The registry's enum
        // exists so a HAND-written switch can have cases; a generated
        // one needs no such handle, and taking the symbol directly
        // removes the one place the two could disagree — the derived
        // enumerator and the registry's canonical one are not the same
        // string, and the first version of this generator proved it by
        // emitting `RopeBf16` where the registry says `RopeFull`.
        // Calls the LAUNCHER, not the flat entry point. The shim is a
        // PROOF -- it compiles a forward with the header in scope, so a
        // wrong row does not build -- and it is generated into a test's
        // temp dir rather than into the archive. The driver is C++ and
        // can call C++; a flat ABI matters for a consumer that is not,
        // and there is none yet. When there is, this switches to
        // `entry_name` and the shim joins the build.
        out.push_str(&format!(
            "if (sym == \"{}\"{}) {{\n    {}{}(\n        {});\n    return true;\n}}\n",
            k.symbol,
            guard,
            if k.returns.is_empty() { "" } else { "(void)" },
            cpp_path(k.symbol),
            binds.join(",\n        "),
        ));
    }
    out
}

